#!/usr/bin/env bash

# ==============================================================================
# CloudGallery - Automated AWS Serverless Infrastructure Deployment Script
# Provisions: Cognito, S3, DynamoDB, Lambda, API Gateway, S3 Events, CloudFront
# ==============================================================================

set -e

echo "========================================================"
echo "  🚀 Starting CloudGallery AWS Serverless Deployment   "
echo "========================================================"

# Default variables
STACK_NAME="${STACK_NAME:-cloudgallery-stack-prod}"
AWS_REGION="${AWS_REGION:-us-east-1}"
ENVIRONMENT="${ENVIRONMENT:-prod}"

echo "📍 Target AWS Region : ${AWS_REGION}"
echo "📦 CloudFormation Stack: ${STACK_NAME}"
echo "🌐 Environment Stage   : ${ENVIRONMENT}"
echo "--------------------------------------------------------"

# 1. Check prerequisites
if ! command -v aws &> /dev/null; then
    echo "❌ Error: AWS CLI is not installed. Please install aws-cli first."
    exit 1
fi

if ! command -v sam &> /dev/null; then
    echo "❌ Error: AWS SAM CLI is not installed. Please install sam-cli first."
    exit 1
fi

# 2. Build SAM Application
echo "⚙️  Building SAM Lambda functions and backend artifacts..."
sam build --use-container --template-file template.yaml

# 3. Deploy SAM Stack
echo "🚀 Deploying Serverless CloudFormation stack via AWS SAM..."
sam deploy \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
  --parameter-overrides Environment="${ENVIRONMENT}" CorsAllowedOrigin="*" \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset

# 4. Fetch Stack Outputs
echo "🔍 Fetching deployed resource endpoints and IDs..."

API_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
  --output text)

USER_POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
  --output text)

USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
  --output text)

CLOUDFRONT_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontUrl'].OutputValue" \
  --output text)

ORIGINAL_BUCKET_NAME=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='OriginalBucketName'].OutputValue" \
  --output text)

THUMBNAIL_BUCKET_NAME=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ThumbnailBucketName'].OutputValue" \
  --output text)

DYNAMODB_TABLE_NAME=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${AWS_REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='DynamoDBTableName'].OutputValue" \
  --output text)

echo "--------------------------------------------------------"
echo "✅ Deployment Succeeded!"
echo "📡 ApiUrl             : ${API_URL}"
echo "👤 UserPoolId         : ${USER_POOL_ID}"
echo "🔑 UserPoolClientId   : ${USER_POOL_CLIENT_ID}"
echo "⚡ CloudFrontUrl      : ${CLOUDFRONT_URL}"
echo "🪣 OriginalBucketName : ${ORIGINAL_BUCKET_NAME}"
echo "🖼️  ThumbnailBucketName: ${THUMBNAIL_BUCKET_NAME}"
echo "🗄️  DynamoDBTableName  : ${DYNAMODB_TABLE_NAME}"
echo "--------------------------------------------------------"

# 5. Automatically write to frontend environment file
echo "📝 Updating .env file with live AWS deployment outputs..."

cat <<EOF > .env
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_AWS_REGION="${AWS_REGION}"
VITE_API_GATEWAY_URL="${API_URL}"
VITE_COGNITO_USER_POOL_ID="${USER_POOL_ID}"
VITE_COGNITO_CLIENT_ID="${USER_POOL_CLIENT_ID}"
VITE_CLOUDFRONT_URL="${CLOUDFRONT_URL}"

# Backend / Lambda Resource References
AWS_REGION="${AWS_REGION}"
ORIGINALS_BUCKET="${ORIGINAL_BUCKET_NAME}"
THUMBNAILS_BUCKET="${THUMBNAIL_BUCKET_NAME}"
PHOTOS_TABLE="${DYNAMODB_TABLE_NAME}"
COGNITO_USER_POOL_ID="${USER_POOL_ID}"
COGNITO_CLIENT_ID="${USER_POOL_CLIENT_ID}"
CLOUDFRONT_DOMAIN="${CLOUDFRONT_URL}"
EOF

echo "✨ .env successfully configured!"
echo "To build and preview the React frontend connected to live AWS:"
echo "  npm run build"
echo "  npm run start"
echo "========================================================"
